"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from portfolio.settings.base import *
from portfolio.settings.apps import *
from portfolio.settings.app_vars import *
from portfolio.settings.database import *
# from portfolio.settings.settings import *